### ISSUE TITLE
Playlists with a show item fail to deserialize

### ISSUE THREAD

**Issue by jpochyla** [KaiJewson/aspotify#8]
Hi! It seems that when a playlist contains a show item (or maybe an episode, not sure about the differences here), they fail to deserialize. Example playlist is https://open.spotify.com/playlist/37i9dQZF1DXacZOGa5EAdH.

**Comment by SabrinaJewson** [comment]
Hmm, it seems that [despite the documentation](https://developer.spotify.com/documentation/web-api/reference/object-model/#playlist-track-object) the playlist track object is returning `null` in its `track` field. It's fixed now in 0.7.0 (had to make a breaking release since it replaces the previously non-nullable `item` field with an `Option`).

**Comment by jpochyla** [comment]
Thanks!
